### ISSUE TITLE
DummySubscriptionsSeeder not found 

### ISSUE THREAD

**Issue by takeshiyu** [LaravelDaily/Laravel-Todoist-SaaS#2]
When I do the 

```
php artisan db:seed --class=DummySubscriptionsSeeder
```

will output error:

```
Target class [DummySubscriptionsSeeder] does not exist.
```

**Comment by PovilasKorop** [comment]
@s12i well spotted, this was copied from another project, in here we don't have dummy subscriptions. Will remove from readme, and you should launch just general `php artisan db:seed`
